# ===== 自定义 本机服务端口 配置 ===== #
server:
  port: 1300

spring:
  application:
    name:
  jpa:
    #jpa 配置
    database-platform: org.hibernate.dialect.MySQL5Dialec
    # 是否开启生成表结构
    generate-ddl: false
    # 在日志中打印SQL语句
    show-sql: true
    properties:
      hibernate:
        # 格式化日志中的SQL语句
        format_sql: true
        # 日志级别 ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF
        type: INFO
        # 是否在SQL语句中输出便于调试的注释信息，show_sql=true时有效
        use_sql_comments: true
        # 在一个session中累计多少条SQL之后批量提交，提交后session会清除缓存并关闭
        jdbc.batch_size: 50
        # 通过实体类生成表的策略
        ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.252.129:3306/integration?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: mysql129
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 2
      #最小值
      minIdle: 2
      #最大值
      maxActive: 5
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接1h
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间5h
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  devtools:
    restart:
      enabled: true
# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
# ===== 自定义Logger Config配置 ===== #
logging:
  level:
    team.sun.integration: debug